description = "Amazon Linux 2023"
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image"
  version = "11.2.0"
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:17.3.0"
  version = "17.3.0"
[[buildpacks]]
  uri = "docker://ghcr.io/wilsonrf/aws-lambda-rie:0.0.1"
  version = "0.0.1"
[[extensions]]
  uri = "docker://ghcr.io/wilsonrf/aws-lambda-rie-extension:0.0.1"
  version = "0.0.1"

[lifecycle]
  version = "0.20.4"

[[order]]
[[order.group]]
  id = "paketo-buildpacks/java-native-image"
  version = "11.2.0"
[[order.group]]
  id = "wilsonrf/com.wilsonfranca.aws-lambda-rie"
  optional = true
  version = "0.0.1"
  

[[order]]
[[order.group]]
  id = "paketo-buildpacks/java"
  version = "17.3.0"
[[order.group]]
  id = "wilsonrf/com.wilsonfranca.aws-lambda-rie"
  optional = true
  version = "0.0.1"

[[order]]
[[order.group]]
  id = "wilsonrf/com.wilsonfranca.aws-lambda-rie"
  version = "0.0.1"
/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
[[order-extensions]]
[[order-extensions.group]]
  id = "wilsonrf/com.wilsonfranca.aws-lambda-rie-extension"
  version = "0.0.1"


[build]
image = "ghcr.io/wilsonrf/amazonlinux-al2023-build:0.0.1"
[run]
[[run.images]]
image = "ghcr.io/wilsonrf/amazonlinux-al2023-run:0.0.1"

[stack]
id = "com.wilsonfranca.stacks.amazonlinux.al2023"
run-image = "ghcr.io/wilsonrf/amazonlinux-al2023-build:0.0.1"
run-image-mirrors = ["ghcr.io/wilsonrf/amazonlinux-al2023-run:0.0.1"]
build-image = "ghcr.io/wilsonrf/amazonlinux-al2023-build:0.0.1"